### PR TITLE
changed subdomain name

### PR DESCRIPTION
**Pull request by 9551-Dev**
i want to change the subdomain name so i can put multiple projects onto the single website without having all of them be under GuiH

### CODE REVIEW

**Comment by SquidDev** [comment]
You can create multiple subdomains - feels like it'd be sensible to keep around guih even as just a redirect.

**Comment by 9551-Dev** [comment]
I could do that ye. But won't gh pages redirect all pages to the main one ? 9551-Dev.github.io which rn is guih.madefor.cc

**Comment by 9551-Dev** [comment]
If its possible to have gh pages use several different subdomains for diffirent repos i will grab love.madefor.cc since thats what i was planning on adding

**Comment by SquidDev** [comment]
As long as the repos have different `CNAME` files it should be fine - both `squiddev-cc.github.io` and `skythecodemaster.github.io` have multiple domains.

**Comment by 9551-Dev** [comment]
Ah i see. I will make a different pr then, thanks

**Pull request closed without merging**
