### PR TITLE
Update domains.py

### PR DESCRIPTION
**Pull request by MinecraftedGaming**

### CODE REVIEW

**Comment by MinecraftedGaming** [comment]
i just realized that i messed up how i made the page going to add another comment when i fix it to work with this pull request

**Comment by MinecraftedGaming** [comment]
should be good now. do i have to redo the pull request due to failed check?

**Comment by SquidDev** [comment]
You shouldn't need to redo it, just fix the ordering. `mg` should go directly after `metis`.

**Comment by MinecraftedGaming** [comment]
`metis` does not show on my end for some reason could you copy the line so I can paste it before mg

**Comment by MinecraftedGaming** [comment]
ordering fixed in commit `f78766fec980ac461296ec4977c04738ada9d513` (man thats a long id)

**Comment by MinecraftedGaming** [comment]
what should i have in the CNAME file to get the site to work through mg.madefor.cc

**Pull request merged**
