### PR TITLE
Update domains.py

### PR DESCRIPTION
**Pull request by Apethesis**
transferred guih to 9551 and taken pecdocs
sorry for bothering you squid

### CODE REVIEW

**Comment by SquidDev** [comment]
Can you sort this domain in the list please?

**Comment by Apethesis** [comment]
sorry if im dumb but
how do i sort it?

**Comment by SquidDev** [comment]
Put `pecdocs` between `music` and `phileos`.

**Comment by Apethesis** [comment]
done

**Comment by 9551-Dev** [comment]
Hello

**Comment by Apethesis** [comment]
> Hello

fat

**Pull request merged**
